import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8081/api';
const App=()=>{
 const [projects,setProjects]=useState([]),[selected,setSelected]=useState(null),[deps,setDeps]=useState([]),[name,setName]=useState(''),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const r=await fetch(`${API}/projects`);setProjects(await r.json())}catch(e){setError('Backend is not reachable. Start the API and try again.')}};
 useEffect(()=>{load()},[]);
 const open=async(id)=>{setSelected(await (await fetch(`${API}/projects/${id}`)).json());setDeps(await (await fetch(`${API}/projects/${id}/dependencies`)).json())};
 const create=async e=>{e.preventDefault();if(!name.trim())return;setBusy(true);setError('');try{const r=await fetch(`${API}/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});if(!r.ok)throw new Error();const p=await r.json();setName('');await load();await open(p.id)}catch(e){setError('Could not create the project.')}finally{setBusy(false)}};
 const scan=async()=>{if(!selected||!file)return;setBusy(true);setError('');try{const fd=new FormData();fd.append('file',file);const r=await fetch(`${API}/projects/${selected.id}/scan`,{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.message||'Scan failed');setSelected(data);await load();await open(selected.id);setFile(null);document.getElementById('pom').value=''}catch(e){setError(e.message||'Scan failed.')}finally{setBusy(false)}};
 return <div className="shell">
  <header><div><span className="eyebrow">DEVELOPER SECURITY</span><h1>Dependency Sentinel</h1><p>See what your Java project depends on — starting with a clean Maven scan.</p></div><div className="status"><span className="dot"/> Phase 1</div></header>
  {error&&<div className="error">{error}</div>}
  <main>
   <aside><div className="panel"><h2>Your projects</h2><form onSubmit={create} className="create"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Project name"/><button disabled={busy}>Create</button></form>{projects.length===0?<div className="empty">Create your first project.</div>:projects.map(p=><button className={`project ${selected?.id===p.id?'active':''}`} key={p.id} onClick={()=>open(p.id)}><span>{p.name}</span><small>{p.dependencyCount} deps</small></button>)}</div></aside>
   <section>{!selected?<div className="hero"><div className="heroIcon">DS</div><h2>Start with one <span>pom.xml</span></h2><p>Create a project, upload its Maven dependency file, and get a searchable dependency inventory in seconds.</p><div className="steps"><div><b>1</b><span>Create project</span></div><div><b>2</b><span>Upload pom.xml</span></div><div><b>3</b><span>Review dependencies</span></div></div></div>:<div className="content"><div className="top"><div><span className="eyebrow">PROJECT</span><h2>{selected.name}</h2></div><div className="score"><strong>{selected.securityScore}</strong><span>security score</span></div></div><div className="cards"><div><span>Dependencies</span><strong>{selected.dependencies}</strong></div><div><span>Vulnerabilities</span><strong>{selected.vulnerabilities}</strong></div><div><span>Outdated</span><strong>{selected.outdated}</strong></div><div><span>Conflicts</span><strong>{selected.conflicts}</strong></div></div><div className="scanbox"><div><h3>Scan Maven project</h3><p>Upload the project's <code>pom.xml</code>. Phase 1 stores direct dependencies only.</p></div><label className="upload"><input id="pom" type="file" accept=".xml" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?file.name:'Choose pom.xml'}</span></label><button onClick={scan} disabled={!file||busy}>{busy?'Scanning…':'Scan project'}</button></div><div className="table"><div className="tableHead"><h3>Dependencies</h3><span>{deps.length} found</span></div>{deps.length===0?<div className="empty">No scan yet. Upload a pom.xml to populate this list.</div>:<table><thead><tr><th>Dependency</th><th>Version</th><th>Scope</th><th>Type</th></tr></thead><tbody>{deps.map(d=><tr key={d.id}><td><b>{d.artifactId}</b><small>{d.groupId}</small></td><td>{d.version}</td><td>{d.scope}</td><td><span className="pill">Direct</span></td></tr>)}</tbody></table>}</div></div>}</section>
  </main>
  <footer>Phase 1 • Maven dependency inventory • Vulnerability intelligence arrives later</footer>
 </div>
};createRoot(document.getElementById('root')).render(<App/>);
